# determine mode of compilation
DEBUG  = NO 
# choose solver
SOLVER = 
# name the compilation targets
TARGET = test2 tester 

# include configuration file
include $(INSILICOROOT)/config/convenience.mk
