# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = SUPERLU
# name the compilation targets
TARGET = elasticLagrange rigidBodyEuler rigidBodyLagrange elasticEuler

# include configuration file
include $(INSILICOROOT)/config/convenience.mk


