# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = 
# name the compilation targets
TARGET = areaVolume

# include configuration file
include $(INSILICOROOT)/config/convenience.mk



