# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = SUPERLU
# name the compilation targets
TARGET = nucleus

SPACEDIM=2
APPFLAGS  = -DSPACEDIM=$(SPACEDIM)

# include configuration file
include $(INSILICOROOT)/config/convenience.mk


