# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = SUPERLU
# name the compilation targets
TARGET = dirichlet  nonlinearHeat  convection

TESTMK=nonlinearTest.mk convectionTest.mk


# include configuration file
include $(INSILICOROOT)/config/convenience.mk
