# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = 
# name the compilation targets
TARGET = unstructured structured
# spatial dimension
SPACEDIM=2

# pass value to application flags
APPFLAGS=-DSPACEDIM=$(SPACEDIM)

# include configuration file
include $(INSILICOROOT)/config/convenience.mk

