# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = SUPERLU
# name the compilation targets
TARGET = spherical nut oneDimensional

SPACEDIM=1
APPFLAGS  = -DSPACEDIM=$(SPACEDIM)

# include configuration file
include $(INSILICOROOT)/config/convenience.mk


