# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = SUPERLU
# name the compilation targets
TARGET = linearElastic compressible incompressible

# include configuration file
include $(INSILICOROOT)/config/convenience.mk


