# determine mode of compilation
DEBUG  = NO
# name the compilation targets
TARGET = smf2smf
# destination folder of binaries
BIN=$(INSILICOROOT)/tools/bin

# include configuration file
include $(INSILICOROOT)/config/convenience.mk

all: $(TARGET) install
