# determine mode of compilation
DEBUG  = YES
# choose solver
SOLVER = 
# name the compilation targets
TARGET = interface

SPACEDIM=2

APPFLAGS=-DSPACEDIM=$(SPACEDIM)
# include configuration file
include $(INSILICOROOT)/config/convenience.mk

